version: '2'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dbperson
  redis:
    image: "redis:alpine"
    container_name: redisdb
    ports:
      - "6379:6379"
  logback:
    build: .
    restart: always
    ports:
       - "80:80"
    depends_on:
      - mysqldb
      - redis